package admin

const (
	keyError      = "error"
	keyDatasetID  = "dataset_id"
	keyAction     = "action"
	keyFrom       = "from"
	keyTo         = "to"
	keyAdminName  = "admin_name"
	keyErrorType  = "error_type"
	keyGameID     = "game_id"
	keyUserID       = "user_id"
	keyStartDate    = "start_date"
	keyEndDate      = "end_date"
	keyUserEmail    = "user_email"
	keyUserUsername = "user_username"
	keySlug            = "slug"
	keyManifestURL     = "manifest_url"
	keyName            = "name"
	keyDatasetType     = "dataset_type"
	keyFileName        = "file_name"
	keyFileSize        = "file_size"
	keyTemplateID      = "template_id"
	keyInviteID        = "invite_id"
	keyUpdates         = "updates"
	keyTheme           = "theme"
	keyDifficulty      = "difficulty"
	keyUsername        = "username"
	entityUser         = "user"
	keyPreviousStatus  = "previous_status"
	keyTargetUsername  = "target_username"
)
