package game

const (
	keyCountdownSecs  = "countdown_secs"
	keyData           = "data"
	keyEloUpdated     = "elo_updated"
	keyEloDelta       = "elo_delta"
	keyNewElo         = "new_elo"
	keyResult         = "result"
	keyType           = "type"
	keyMode           = "mode"
	keyReason         = "reason"
	keyError          = "error"
	keyGameError      = "game_error"
	keyGameID         = "game_id"
	keyWinnerPublicID = "winner_public_id"
	keyPlayersFinal   = "players_final"
	keyUserPublicID   = "user_public_id"
	keyUsername       = "username"
	keyPlayers        = "players"
	keyQuestion       = "question"
	keyQuestionNumber = "question_number"
	keyTotalQuestions = "total_questions"
	keyTimeLimit      = "time_limit"
	keyScore          = "score"
	keyPublicID       = "public_id"
)
